import Head from "next/head";
import { Inter } from "next/font/google";

import Account from "./components/Account";
import Contact from "./components/Contact";
import Calendar from "./components/Calendar";
import Gallery from "./components/Gallery";
import Greeting from "./components/Greeting";
import MainInfo from "./components/MainInfo";
import Map from "./components/Map";
import Notice from "./components/Notice";
import Text from "./components/Text";
import Transport from "./components/Transport";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>유환 ❤ 진솔</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, maximum-scale=1.0" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <div className="container">
        <div className="text">THE WEDDING DAY</div>
        <img src={`../../picture02.jpg`} className="picture" />
        <MainInfo />
        <Text />
        <Greeting />
        <Calendar />
        <Map />
        <Transport />
        <Account />
        <Contact />
        <Gallery />
        <Notice />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossOrigin="anonymous"
        ></script>
      </div>
    </>
  );
}
